### ISSUE TITLE
首页分类下无文章

### ISSUE THREAD

**Issue by ma3252788** [MingliangLu/WeTypecho#11]
主页最新发布下面会有文章列表，但是点击各个分类之后，却显示该分类没有文章。
![](http://filessl.machunjie.com/blog/file/20190416115833.png)
![](http://filessl.machunjie.com/blog/file/20190416115858.png)

**Comment by ma3252788** [comment]
开发者工具提示：
![](http://filessl.machunjie.com/blog/file/20190416120527.png)

**Comment by ma3252788** [comment]
您好，我注释了
//item.thumb = item.thumb[0].str_value;
这条语句之后，仍然是无文章~

**Comment by idealclover** [comment]
Fixed in my branch [here](https://github.com/MingliangLu/WeTypecho/tree/idealclover_dev).
Tell me if there're still bugs

**Comment by ma3252788** [comment]
> Fixed in my branch [here](https://github.com/MingliangLu/WeTypecho/tree/idealclover_dev).
> Tell me if there're still bugs
我修改了action.php，结果还是一样的。。
![](http://filessl.machunjie.com/blog/file/20190517200350.png)
