### ISSUE TITLE
点击分享到朋友圈的话无法生成图片

### ISSUE THREAD

**Issue by liunijia** [MingliangLu/WeTypecho#2]
点击分享到朋友圈的话无法生成图片，希望解决，谢谢啦！

**Comment by idealclover** [comment]
可能时downloadFile域名的问题，需要在小程序后台进行设置
blog地址应当在小程序后台的downloadFile域名列表中
[link](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html)
