### ISSUE TITLE
不错的项目。towxml我发布了新的3.0版本。建议更新。

### ISSUE THREAD

**Issue by sbfkcel** [MingliangLu/WeTypecho#21]
RT

**Comment by idealclover** [comment]
是这样的，我之前尝试过升级到 3.0，但是底层出了点问题

似乎之前的版本底层只依赖 markdown-it，所以比较方便

新版本依赖有些复杂，有些 bug 没办法解决于是作罢 > <

另外就是现在发了新项目 [idealclover/UniTypecho](https://github.com/idealclover/UniTypecho) 所以就暂时没有再帮项目主更新了w
