### ISSUE TITLE
["connectSocket"] 字段需为 number

### ISSUE THREAD

**Issue by parisnovs1471** [MingliangLu/WeTypecho#3]
上传错误，原因：Error: appJSON["networkTimeout"]["connectSocket"] 字段需为 number

**Comment by jcorg** [comment]
> 上传错误，原因：错误：appJSON [“networkTimeout”] [“connectSocket”]字段需为数

最新版的微信小程序开发工具会报这个错误，我是直接把这两个字段给去掉了
